### ISSUE TITLE
ASIO Plugin implementation

### ISSUE THREAD

**Issue by ujifgc** [pkviet/obs-studio#10]
Hello.

I saw your thread on OBS Mantis https://obsproject.com/mantis/view.php?id=834 and decided to show my work on a similar plugin:

https://github.com/ujifgc/obs-studio/tree/asio2

Right now my plugin works with one device and one input channel. You can add the input in OBS sources menu by selecting `AudioInputASIO2`.

Issues I'm having:

1) Sometimes the plugin initializes wrong and the sound is distorted. Re-initializing (with show/hide button) helps half of the times.
2) During the first 5 or so minutes of streaming or recording OBS can decide to add 23 ms to its circle buffer causing 23 ms silent gap in the resulting audio stream.

Issues I overcame with a separate thread, a separate realignment buffer and timestamp approximation:

1) Popping and crackling when tried to call `#obs_source_output_audio` directly from ASIO callback `#bufferSwitchTimeInfo`
2) Occasional popping and crackling when pushing `#obs_source_output_audio` with the number of frames other than 441 (for 44100 sampling rate)

I'm hoping to help in implementing a great and stable ASIO plugin for OBS Studio.

**Comment by pkviet** [comment]
Hi
Welcome on board.
With Andersama we already have a fully working plugin for one device. Any
input channels, bitdepth, sample rate are working.User can select up to 8
input channels in any order (limitation to 8 us because obs does not
support more at output). If a device has more than 8, you select any subset
you want out of the input channels.
Check my repo obs-asio. There are screen caps.
Or git clone my obs-studio repo and select the asiort branch.
We didn't use directly the asio sdk but leveraged RtAudio library. This was
easy to do.

The various exchanges on mantis you are seeing are related to our attempt
to implement a workaround to the most serious defect of asio: just a single
driver can be loaded at any time . This is a defect in COM implementation
which us very well-known and prevents multiple devices use. Check for a
codeguru.com link in the various notes in mantis for details .

We're in obs-dev irc if you want to chat.



Le 20 janv. 2018 7:28 PM, "Igor Bochkariov" <notifications@github.com> a
écrit :

**Comment by ujifgc** [comment]
Yes, I built your plugin and tested it with Voicemeeter virtual ASIO inputs and hardware Behringer UMC204HD. Both do occasionally crackle and pop. I'm on Windows 8.1.

Do you get clean sound from your devices? What devices are you using on what OS?

**Comment by pkviet** [comment]
yep, clean sound;
you need to select float though as bitdepth.
I tested on esp esi 1010e (pcie card with 8 in/ 8 out), maudio fast track ultra (8 in too), on rearoute from reaper

**Comment by Andersama** [comment]
@ujifgc I take it that you don't get cracks and pops using either of those normally. I'm getting pretty clean audio Win 10, there's the occasional crackle / pop. they're spaced pretty far apart though.

**Comment by pkviet** [comment]
you can try also the asiobass branch; tell me if it works better. To build you'll need the bassasio library. The dll and lib are already built in the zip. https://www.un4seen.com/
You'll need to copy the dll in rundir/obs-plugins/bin/64bit and in cmake you have to give:
BASS_ASIO_LIB path to bassasio.lib and BASS_ASIO_INCLUDE_DIR path to bassasio.h
Be careful: in the zips there are two versions of dll and lib (64 and 32 bit)
It works fine for me; if u have pops and cracks tell us

**Comment by ujifgc** [comment]
Well, when I interface with Voicemeeter through OBS WASAPI, I get occasional (one in 5-10 minutes) silence gaps of 20 or 40 ms. I came to conclusion that it's Voicemeeter virtual input driver flaw, because bit-exact dump into a file of what OBS WASAPI gets is already has these gaps.

These gaps though do not sound like pops and crackles.

Pops and crackles I get are not stable, they can frequent on the first 10 seconds, then no crackles for a minute, then again some. I eliminated these in my implementation with buffer realignment and synchronization.

**Comment by Andersama** [comment]
Were you using the sdk directly or a library of some sort, because you would need timestamps for the incoming samples to pull that off correct?

**Comment by Andersama** [comment]
For RtAudio,  the source code's online so if it's an issue that the library could handle by managing the bufferswitch callback differently I can point you to the line numbers where that happens.

BASS is a prebuilt library, I haven't really had time to poke around it myself, but pkviet got it working.

ASIO++ is a library he found from a codeguru article written 9 years ago. There's a lot of code that outright didn't work so I've been fixing bugs and trying to get it implemented, it's not nearly as wrapped up as the rest.

**Comment by ujifgc** [comment]
I take the timestamps from the device when it calls bufferSwitchTimeInfo and place them in a buffer aside from the actual audio data. Then I signal an event and a waiting thread checks if there's enough data in the buffer to fill 441 or 480 (I have no idea why it works better) samples for OBS. If there's enough samples, I take them and interpolate a new timestamp for OBS that would be proportionally between the original timestamps.

**Comment by Andersama** [comment]
So you managed an intermediate buffer then, the way we have it, as you've probably poked around already is straight from the callback directly into OBS w/ the timestamp from when obs's output about to start.

OBS was appending buffer's anyway up til 1024, so we didn't bother w/ an intermediate buffer. Clearly that's not the way to go about it if you've managed to remove cracks and pops.

**Comment by ujifgc** [comment]
Yes. At first I tried this approach with the call of OBS routines from the ASIO callback, but it crackled occasionally. For me it was unacceptable. I'm not sure if it's a good idea to call big functions from a fast ASIO callback (it can frequent like every 5 ms or less).

**Comment by Andersama** [comment]
Here's a thought though, OBS is always consuming 1024 samples, in the bass library I think we can set the buffer to match, and then presumably the buffers should align and the callbacks shouldn't be so frequent.

I'm testing out the BASS branch and I seem to get even less crackles and pops.

**Comment by Andersama** [comment]
Here's RtAudio's approach btw: https://github.com/thestk/rtaudio/blob/ce13dfbf30fd1ab4e7f7eff8886a80f144c75e5d/RtAudio.cpp#L2871
they used the old bufferswitch, not the bufferSwitchTimeInfo

**Comment by Andersama** [comment]
Looking at your code, you set up in the same way I thought to do w/ a second thread reading like how wasapi was capturing audio.

And it's WAY cleaner, nice.

**Comment by ujifgc** [comment]
Yes, I used OBS WASAPI as a prototype and ASIO SDK files with minimal Unicode fixes.

**Comment by Andersama** [comment]
I think you might be able to incorporate the library I'm trying to get working to the full extent. I was working on the asio++ branch, the idea is to isolate drivers w/ thread local storage. I messed up horribly managing an intermediate buffer w/ multiple threads. But if we can get that approach working we can have a threaded approach where each source reads off of a device intermediary buffer.

**Comment by ujifgc** [comment]
So the idea is to make several OBS sources to read from different ASIO channels?

**Comment by Andersama** [comment]
I wish I could post an infographic, the idea was isolate each driver so that they all called their own specific callback.

Ideally they'd write to an intermediate buffer of some sort.

From that point, when sources are added they read off of the intermediate device buffers that are available. Would give us multi device and multi source*

I haven't gotten asio++ to the point where we capture anything with it, not quite that far yet.

**Comment by pkviet** [comment]
@ujifgc not on irc ? would be simpler than having these back and forth
