### ISSUE TITLE
More recent OSX build

### ISSUE THREAD

**Issue by matiaspl** [pkviet/obs-studio#16]
Is there any chance for a downloadable OSX build with all the recent bells and whistles of your ingenious obs-studio fork (proper audio mixer, dynamic bitrate and multichannel audio)?

**Comment by pkviet** [comment]
i'll do it but i'm quite busy and thing is building the installer on macOS is a pain ; some I built seem to work with my updated ffmpeg binaries  only if the mac is recent (intel gen 7 +). So i've to sort out these issues before offering an installer ... And i don't talk of the Qt bugs specific to mac.

**Comment by matiaspl** [comment]
Thanks for the information. Is a linux build more generic in these terms?

**Comment by pkviet** [comment]
linux is a breeze to build, i could offer debs probably

**Comment by pkviet** [comment]
my mac is broken so I can't provide macOS builds unfortunately. If people want to donate so that I acquire a new mac, feel free to ping me (pkv.stream () gmail.com ).

**Comment by pkviet** [comment]
a solution would be to setup CI. I'll study that.

**Comment by pkviet** [comment]
I've released a mac binary after sponsorship. Check the Release section. CI has been setup so there will be regular mac updates.
