### ISSUE TITLE
FFMPEG Binaries

### ISSUE THREAD

**Issue by jprjr** [pkviet/obs-studio#17]
Hi there - I didn't know if there was some way you could share the pre-compiled FFMPEG dependencies, or a script for compiling them, etc.

Thanks in advance! This fork is awesome.

**Comment by pkviet** [comment]
You can get the ffmpeg dll from the installation folder: Program Files/obs-studio MC/bin
For compilation, I use visual studio 2017 and this tool: https://github.com/ShiftMediaProject/FFVS-Project-Generator
Sorry for answering only now.
