### ISSUE TITLE
webm not rendering alpha / display issues

### ISSUE THREAD

**Issue by coffeeratmedia** [pkviet/obs-studio#21]
the alpha's arent being loaded / render correctly here a example of it as u can see there also a issue with the gradient in the video file being loaded

![how its displaying](https://user-images.githubusercontent.com/56743736/67132624-1c277280-f255-11e9-8a81-5073ba94e4e6.PNG)

here a sample when the same webm file is laoded into offical obs release v24
![Capture](https://user-images.githubusercontent.com/56743736/67132815-c4d5d200-f255-11e9-969b-9256592296cb.PNG)

here's a log file ->https://obsproject.com/logs/38eNffeZxNdxglVP

**Comment by pkviet** [comment]
~~do you have these issues with regular build of obs ? there's been a lot of issues related with alpha, webm files even on the official build.~~
edit: so the issue in regular builds is with trying to have hardware acceleration when decoding the webm with alpha.
I think the issue you're having is with my ffmpeg dll; I compiled only the codec support i needed; i don't use webm/alpha/vp9 ...
I might fix this in the next release. But this is not high priority for me.

**Comment by coffeeratmedia** [comment]
ok totally understanable thanks for clearing that up

**Comment by pkviet** [comment]
can you drop somewhere the webm file with alpha ? this will help me test my dll

**Comment by pkviet** [comment]
update: i've fixed the issue; i'll post a new build in the next few days.

**Comment by pkviet** [comment]
Fixed in the latest release.
