### ISSUE TITLE
Is this how you open an issue? OBS ME

### ISSUE THREAD

**Issue by aranhawaii** [pkviet/obs-studio#22]
Hey so we spoke in emails, but bringing this here so people can potentially benefit from the response. 

My audio was totally crazy when I installed your OBS ME. I installed it on a second PC and it was great. But for some reason the 1st PC did this: https://www.youtube.com/watch?v=BdwKPUqUueM&feature=youtu.be

This was just desktop audio, playing music on Spotify. I did the same on my second PC and it worked great.

Any ideas? I wonder if there are any settings on Windows that I should start with to make sure it's not an issue with my OS sound settings?

If you need a log from OBS, let me know?

**Comment by pkviet** [comment]
sorry, i really have no idea why this works on one pc but not the other. How is your desktop audio set up on the pc where it fails to work ? i'd investigate the diffrence in the setups.
