### ISSUE TITLE
Which Qt build to  DL?

### ISSUE THREAD

**Issue by jackjack86** [pkviet/obs-studio#23]
Qt Build 5.10.1 is the one in the "official" build instructions but these can no longer be downloaded. v5.12.2 and v5.14.2 both give me config errors.

**Comment by pkviet** [comment]
I use 5.10.1 too. Yeah, can't be found unfortunately. I have errors too on
5.14.2.
I'm gonna release a build in the next few days.

**Comment by jackjack86** [comment]
maybe a repository could be put up? I'd need to re-read the Qt GPL

**Comment by pkviet** [comment]
new build is out

**Comment by jackjack86** [comment]
Thanks! Which branch? master says 4-13-20...

Edit: accidental close

**Comment by pkviet** [comment]
i had forgotten that we store qt 5.10.1: [here](https://cdn-fastly.obsproject.com/downloads/Qt_5.10.1.7z)
(though that's preobably moot by now)
