### ISSUE TITLE
Stinger Transitions not working from obs studio (official)

### ISSUE THREAD

**Issue by jackjack86** [pkviet/obs-studio#24]
Yeah, methinks my stinger transitions aren't being decoded. They were fine in official. Does your build require certain setting be enabled at render? running 25.0.4 release. 24.0.3 works tho, same encode.

**Comment by pkviet** [comment]
yes confirmed; I have a deps issue which I'll fix in the next few days.

**Comment by pkviet** [comment]
should be fixed with v25.0.5beta. Check and report.

**Comment by jackjack86** [comment]
I'm getting an NSIS error when trying to install the beta...

**Comment by jackjack86** [comment]
ok, got it working. Never encountered this error type before but google prevails lol. Stinger transitions are indeed working.

**Comment by pkviet** [comment]
oh sorry; i re-uploaded the binary, should be fine now

**Comment by jackjack86** [comment]
Yeah i had an issuewith a dll file not installing from a clean install. I'll give it a try with new binary

**Comment by jackjack86** [comment]
nope, getting an error from libcrypto-1_1.dll with current beta installer when trying to execute.

**Comment by jackjack86** [comment]
for some reason only reinstalling from 24.0.3 resolves the dll error

**Comment by pkviet** [comment]
that's really odd; I clean installed with the binary and it worked. I just made sure to uninstall previous OBS ME  25 version.

**Comment by jackjack86** [comment]
well, I'm not having any issues. might be something weird that is specific to my rig, idk
