### ISSUE TITLE
Auxiliary outputs

### ISSUE THREAD

**Issue by reustaquiojr** [pkviet/obs-studio#25]
Would it be possible to have specific output interfaces for each audio BUS on master mixer ? 

In some scenarios audio minus is necessary, it would be a very valid feature

Just like Newtek Tricaster* or VMIX Audio Buses capabilities!

* https://support.newtek.com/hc/en-us/articles/222870068-Advanced-Configuration-Audio-
** https://www.vmix.com/help23/index.htm?AudioOutputs.html

PS: Great job !

**Comment by pkviet** [comment]
this is possible in theory. There's a work in progress for monitoring buses on main obs. When it's merged, you'll be able through monitoring to send the audio tracks to any hardware or virtual audio output. (wasapi or coreaudio, not asio because it's not been written).

**Comment by pkviet** [comment]
this will be available in next release of OBS ME with inclusion of audio monitor filter.
