### ISSUE TITLE
hotkey for monitoring toggles

### ISSUE THREAD

**Issue by tconley** [pkviet/obs-studio#26]
@pkviet Awesome project! - your monitoring icons are great - after trying to build regular obs-studio with some of the changes to allow for toggling audio monitoring I found your OBS-ME!  I'll be using this for my streaming from now own because of this much needed feature!

Is it possible to add hotkey toggles for each audio track?  I'm currently doing this by using a 3rd party hotkey app to call monitoring toggles via obs-websockets.

**Comment by pkviet** [comment]
Done: https://github.com/pkviet/obs-studio/releases/tag/25.0.8win
