### ISSUE TITLE
Updater

### ISSUE THREAD

**Issue by aranhawaii** [pkviet/obs-studio#27]
Is it possible for me to update your ME version? When the popup happens saying they've released a new version, and I click to update, it closes OBS and has the "waiting for OBS to close" warning up, but then just sits on that as if OBS hasn't closed yet.

**Comment by aranhawaii** [comment]
Worth noting, I had to Control Alt Delete and then close an instance of OBS that was still running. Perhaps something is going on that causes OBS to appear to be closed but it's not?

**Comment by pkviet** [comment]
Hello,
Don't update. The updater links to vanilla obs so there will be issues. I
don't have the infra to host the files.
I've disabled the updater , it will be removed in a new update in a few
days.

**Comment by pkviet** [comment]
fixed in current releases
