### ISSUE TITLE
Master volume level does not affect ndi output

### ISSUE THREAD

**Issue by PeterAkakpo** [pkviet/obs-studio#30]
muting the sound on the master mixer mutes the sound on the ndi output, but changing the volume level on the master mixer does not affect the ndi output.

**Comment by pkviet** [comment]
I'll need more details.
How did you test ? your ndi output was sent to which app ?
In your ndi output settings, did you select Preview or Main output ? are you in studio mode or not ?
also provide a log.

**Comment by pkviet** [comment]
Ok i can confirm the bug; there's indeed a regression.
I haven't pinpointed where yet.

**Comment by pkviet** [comment]
I have found the fix for the bug. I'll push the code in a short while. This will be in the next release which will be when vanilla obs 26 is out.

**Comment by pkviet** [comment]
Fixed in current v26 release
