### ISSUE TITLE
NDI Runtime not found

### ISSUE THREAD

**Issue by Mishasama** [pkviet/obs-studio#32]
OBS-Studio-ME-25.0.8

![image](https://user-images.githubusercontent.com/54498172/91000860-19c83e80-e605-11ea-9fe0-5281f2d2284d.png)
I had installed this pack already.

**Comment by pkviet** [comment]
mmh i have no idea why you get that then if you've already isntalled the runtime. It works on my side. Arre you running obs as admin or regular user ? how did you install the runtime ?

**Comment by Mishasama** [comment]
If I run as admin, it displays nothing, the process just disappears itself and nothing shows up.
If I run as a regular user, it will show up this error.

I download this runtime from the error given, and then run the installer as admin, then all next.

Maybe it can't run if I had run the regular version before?

**Comment by pkviet** [comment]
i'm closing; feel free to reopen if you still experience the issue; can't repro on my side.
