### ISSUE TITLE
Configurations of Vst Plugins

### ISSUE THREAD

**Issue by mavkeysound** [pkviet/obs-studio#34]
Hi. I cant save the configurations or presets of VST plugin.

**Comment by mavkeysound** [comment]
Hi. Its me again. 
Some fix for that problem? Only can use the Extension vst but no VST plugin because i cant save the preset of the VST. When i re open OBS ME i lose the presets.

**Comment by pkviet** [comment]
Which filter are you using ? Native obs vst filter ? Or the juce vst2 vst3 filter which I ship ?
Do you have the issue on vanilla obs ?

**Comment by mavkeysound** [comment]
The vst2 and vst3 filter... the native obs vst works fine. But the others vst2 and vst3 dont save presets in each vst... i have this issue in obs music edition only.

**Comment by somedolphin** [comment]
Hey there, thanks so much for OBS music edition! I’m also having this problem with the VST3 plugins not saving their settings. It’s amazing they are loading so thanks you for all your work!
Blessings..

**Comment by pkviet** [comment]
I fixed the issue; the fix will be available in next release (in a few days).

**Comment by somedolphin** [comment]
Cool Pkviet! Thank you!
