### ISSUE TITLE
Plugins for ME edition

### ISSUE THREAD

**Issue by aranhawaii** [pkviet/obs-studio#35]
Can you explain how I can get plugins working for ME edition?

**Comment by pkviet** [comment]
you need to compile them against the libobs version of obs ME; the libobs library differs from vanilla one due to more extensive audio capabilities.

**Comment by aranhawaii** [comment]
Where do I get that version? Sorry I'm terrible at github.

**Comment by benshure58** [comment]
hola QUISIERA SABER COMO UTILIZAR MI DAW CUBASE 5 PARA COMPARTIR MI MEZCLA O GRABACION DEL ESTUDIO MEDIANTE OBS Y DISCORD Y/O ZOOM CON MIS ALUMNOS ? TENGO UNA INTERFAZ DE SONIDO TASCAM US1800

**Comment by pkviet** [comment]
> hola QUISIERA SABER COMO UTILIZAR MI DAW CUBASE 5 PARA COMPARTIR MI MEZCLA O GRABACION DEL ESTUDIO MEDIANTE OBS Y DISCORD Y/O ZOOM CON MIS ALUMNOS ? TENGO UNA INTERFAZ DE SONIDO TASCAM US1800

please use english; it's a bit rude to expect people to understand you in your language. Secondly, don't hijack other people's issues. Create your own one. Thirdly, don't use upper case: that's like screaming and also rude. If you don't know what is Netiquette, google it.
As to your question, try with vanilla obs and look for guides; there are tons of those on the web. Regarding your interface, I don't own it, but I have one from that brand so it should work fine.

**Comment by pkviet** [comment]
> Where do I get that version? Sorry I'm terrible at github.

you need to compile first my obs ME, which will create a libobs.lib and dll. Then you'd have to compile the plugins you want against thoe libs. If you have never compiled anything, forget the suggestion. Most plugins of obs vanilla just won't be compatible with obs ME.
