### ISSUE TITLE
OBS ME 25 - Monitoring happening even if I de-select it.

### ISSUE THREAD

**Issue by aranhawaii** [pkviet/obs-studio#37]
The output audio is still going to my monitoring device, even though I have deactivated monitoring in the mixers by greying out the headphones icon. If I enable it, it plays twice. I also noticed that the options for Monitor Only and Monitor+Output are no longer in the Advanced Audio Properties menu. How do I stop this?

Basically, I can't get it to stop sending monitoring without changing the Monitoring Device selected in Settings.

**Comment by pkviet** [comment]
there's a bug with monitoring indeed which I fixed; but I haven't released it in current obs ME. I'm waiting for obs 26 to be released in order to incorporate all recent additions. Should be soon enough.

**Comment by pkviet** [comment]
fixed in 26.0.2
