### ISSUE TITLE
OBS ME 25/26 Monitoring switching problem

### ISSUE THREAD

**Issue by x0rx** [pkviet/obs-studio#39]
Hi, now solved the issue #38 with ME 26 monitoring, let me explain the problem I see with switching, both in v25.0.8 and in pre-release 26.0.2.

- On input mixer, there´s no problem enabling/disabling monitor icon switch. Add or substract from the selection. Sound follows icon on/off status.
- On master mixer, with audio coming to 2 tracks, Start monitoring track1, then enabling monitoring on track2 disables track1 icon, but sound from track1 is not silenced. Sound doesn't follow icons on/off status.
- And this later behaviour happens when switching from input mixer to master mixer: Start with two inputs on input mixer with monitoring active, then enabling monitoring on master mixer track1, disables the two icons from input mixer, but sound from this two inputs remains active. 

So there´s two things here:
1) Inside both groups (input & master mixer) things should work in add/substract to group selection mode. 
2) Switching from one group to the other should work in exclusive mode. One group active at a time.

Let me know if you need something more @pkviet . Thanks.

**Comment by pkviet** [comment]
ok i see, i botched the soloing of tracks.

**Comment by pkviet** [comment]
it's fixed. I'll post a build once CI is done.

**Comment by pkviet** [comment]
test this: https://github.com/pkviet/obs-studio/actions/runs/312235298
(artifact not the linux zip)

**Comment by x0rx** [comment]
Perfect. Problem solved. This should close issue #37 also.

Many thanks @pkviet !!

**Comment by pkviet** [comment]
closing this issue; bug will be fixed in upcoming 26.0.2
