### ISSUE TITLE
How to add any vst plugin from another directory???

### ISSUE THREAD

**Issue by deenbee** [pkviet/obs-studio#40]
vst plugin folder directory only default please how to add a new path

**Comment by pkviet** [comment]
it's not possible for now but i'll investigate on how to achieve that.

**Comment by Chron-O-John** [comment]
In the meantime you could use a symlink if you only want one specific directory.
cmd -> mklink

**Comment by pkviet** [comment]
On windows the vst3 are loaded from C:\Program Files\Common Files\VST3 and the vst2 from C:\Program Files\Steinberg\VSTPlugins.
The simplest would be to copy your vst there or to make a symlink indeed.
I don't plan on adding custom locations, so closing.
