### ISSUE TITLE
OBS Plugin

### ISSUE THREAD

**Issue by kotexe** [pkviet/obs-studio#41]
Hey. My name is Artyom, I am a marketer from Russia. Found your contacts on github. I'm looking for a person who will write a plugin for obs that will not send sound to broadcast from a specific source. If you can help, I'll tell you more. We will agree on the price.

**Comment by ryantheleach** [comment]
@kotexe Surely you could just disable it in advanced audio properties and make it not send the track to any of the outgoing tracks?

**Comment by kotexe** [comment]
I didn't explain well. The sound from this plugin should be reproduced on the streamer's PC, but the sound should not leak into the broadcast.

**Comment by pkviet** [comment]
I'm not doing any coding for third parties apart from this hobby project, sorry.
Closing since it's unrelated to this project.
