### ISSUE TITLE
Master Mixer does not update the track name after changing the profile.

### ISSUE THREAD

**Issue by Mishasama** [pkviet/obs-studio#42]
**Describe the bug**
As the issue title.

**To Reproduce**
1. Go to 'Output'
2. Change any track name
3. Restart OBS-ME
1. Change to another profile

**Expected behavior**
The track name should change to the new name that stores in another profile.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WIN 10 1809
 - Version 26.0.2

**Additional context**

**Comment by pkviet** [comment]
yeah, i didn't think of profiles indeed. I'll see what I can do for next release.

**Comment by pkviet** [comment]
Fixed in next release. Closing.
