### ISSUE TITLE
Elgato Stream Deck

### ISSUE THREAD

**Issue by Woody2209** [pkviet/obs-studio#44]
in standard OBS 26.0.2 you go to "Tools" and you find "Elgato Remote Control for OBS Studio" but not in OBS Music Edition 26.0.2. (it´s not listed)
Therefore Stream Deck (XL) is not working within "Music Edition".
Thanks
By the way I´m using the latest Windows 10 version and updates.

**Comment by pkviet** [comment]
no it can't work because I changed the libobs library against which the plugins are compiled.
The changes are to enable the expanded audio.
You'd have to self compile the plugin against my libobs (which requires compiling it first). I don't use the plugin so I have no plan to compile it. Sorry !

**Comment by Woody2209** [comment]
thanks for your quick response.  
By the way "Elgato Remote Control for OBS Studio" is no plug-in to install additionally (maybe it was), it´s already integrated in OBS and show´s up when the hardware-controller Elgato Stream Deck is plugged via USB (and Elgato Stream Deck Software is installed).

**Comment by Woody2209** [comment]
I think this is not relevant: Elgato Software Version is 4.9.13177

**Comment by pkviet** [comment]
this is the source code of the plugin https://github.com/elgatosf/streamdeck-obs-plugin; it's installed when you install streamdeck. Obviously it won't install with OBS ME...
Closing the issue.
