### ISSUE TITLE
plugIn obs-websocket

### ISSUE THREAD

**Issue by Woody2209** [pkviet/obs-studio#45]
Hello,
I´d like to use the app "Touch Portal" and therefore I installed Websocket 4.8 PlugIn (https://github.com/Palakis/obs-websocket), but it´s not working in "Music Edition", it´s not listed as "WebSockets server Settings" in "Tools"
Same problem using "Elgato Stream Deck"?
Thanks

[2020-12-08 12-21-57.txt](https://github.com/pkviet/obs-studio/files/5658967/2020-12-08.12-21-57.txt)

**Comment by pkviet** [comment]
Yes identical reasons why it can't work. Sorry. I'm only providing the plugins I use. I can't be expected to ship all third party plugins tbf.
