### ISSUE TITLE
Input Mixer display error with Studio Mode

### ISSUE THREAD

**Issue by Mishasama** [pkviet/obs-studio#47]
**Describe the bug**
The 'Hide in Mixer' will make a duplicate meter when switch scenes.

**To Reproduce**
1. Enable Studio Mode
2. Active scene A (empty)
3. Add a Browser Source
4. Enable 'Control audio via OBS'
5. Active (Steaming) scene B (empty)
6. Select (Preview) scene A
7. Active the Browser Source 'Hide in Mixer', and then deactivate it.
8. Active (Steaming) scene A

**Expected behavior**
I don't know, maybe it should display in properties if 'Hide in Mixer' is active.

**Screenshots**

![image](https://user-images.githubusercontent.com/54498172/105578365-f9262f80-5dc2-11eb-97b7-4f6dc8ea06ce.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 1809

**Additional context**
Or maybe we can add a dock call 'Preview Mixer' like the 'Master Mixer' for the Studio Mode.

Maybe this is the side effect after I replace the Browser plugin.
The 'Control audio via OBS' will make the source's sound mute.

**Comment by pkviet** [comment]
is it only on ME and not regular obs ?

**Comment by pkviet** [comment]
also only with browser source ? (and please on other issue provide feedback as which dll you swapped )

**Comment by pkviet** [comment]
i'm not sure I understand. I can't replicate. Could you make a vid with the bug ?

**Comment by Mishasama** [comment]
Sorry, I have confirmed this issue is on the regular OBS too.
