### ISSUE TITLE
Should remove the ASIO SDK

### ISSUE THREAD

**Issue by Andersama** [pkviet/obs-studio#5]
In the process of going through w/ cmake and setting up the environment* I'll be set up to help debug / program in a bit. You can throw in a git ignore for the folder in the mean time, just make sure that people know to grab the sdk if they're building from this repo:

[http://www.steinberg.net/sdk_downloads/asiosdk2.3.zip](http://www.steinberg.net/sdk_downloads/asiosdk2.3.zip)

Haven't touched this stuff in a while, seems like you're plenty familiar with cmake for anyone showing up later:

ASIO_INCLUDE_DIR in cmake refers to wherever the SDK gets extracted*

**Comment by pkviet** [comment]
yeah sure; 
will take care of it whenever this comes close to completion.
