### ISSUE TITLE
Twitch docks authentication error

### ISSUE THREAD

**Issue by RaynorD** [pkviet/obs-studio#51]
**Describe the bug**
On startup the day after streaming, I get an error message as follows:
```
Failed to authenticate with Twitch:
Failed to parse json: expected value, got 'M' (77)
```

I am able to stream, but all of the twitch docks (chat, activity feed, stream info) are gone and not available in the docks menu.
While troubleshooting, if I disconnect my account, then hit connect again, I get the same error immediately. If I hit the connect button again, it takes me through the login process, then shows the same error and the login is unsuccessful. The login process can then be repeated unsuccessfully, getting the same error.

I have found a workaround, which is opening the official OBS Studio, connecting the account, then closing it and re-opening OBS ME, which then connects successfully. But obviously this is not ideal. I had not opened the official OBS Studio since my last stream with ME.

Log: https://obsproject.com/logs/uJUPebMQavpqrrwH

**To Reproduce**
1. Start OBS ME, connect twitch account successfully.
2. Close OBS ME and wait some period of time (next day-ish)
3. Start OBS ME again.
4. On startup, the error message pops up.

**Expected behavior**
Twitch docks continue working the next time I launch OBS ME.

**Screenshots**
https://i.imgur.com/yuenyCB.png

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Version: 20H2 19042.985

**Additional context**
I have the official OBS Studio installed in parallel, up to date (26.1.1).

**Comment by pkviet** [comment]
This should be fixed in next release. I'm waiting for the final obs 27.
