### ISSUE TITLE
Track Volume isn't saved

### ISSUE THREAD

**Issue by RustyReact** [pkviet/obs-studio#53]
**Describe the bug**
Tracks' volume of Master Mixer area isn't saved. But audio sources' volume of the Input Mixer area is saved.

**To Reproduce**
1. Go to the 'Master Mixer' area
2. Set the volume of Track1 to -30 dB
3. Exit obs and restart obs
4. But volume is initialized again by 0 dB

**Screenshots**

![Screenshot_50](https://user-images.githubusercontent.com/53546539/120201768-ce763880-c1f3-11eb-9eeb-418192bdd626.png)

**Comment by pkviet** [comment]
thanks for the report, i'll check it out for next release

**Comment by pkviet** [comment]
fixed in next release
