### ISSUE TITLE
Track audio doesn't output to NDI when its level is low

### ISSUE THREAD

**Issue by RustyReact** [pkviet/obs-studio#54]
**Describe the bug**
When I set the Track volume of the Master mixer area by -19.9 dB, I can hear the audio via the headphone
But I can't hear it in NDI output. ( I test the audio via Sutio monitor, which is one of NDI tools windows version)

**To Reproduce**
1. Go to 'Master Mixer Area'
2. Set Track1's volume by  -19.9 dB or lower than -19.9 dB
3. You can hear the audio via headphone or speaker of the pc, but You will be not able to hear via NDI output
4. I output to NDI Main output, and monitor it in the Studio monitor

![Screenshot_51](https://user-images.githubusercontent.com/53546539/120202706-e5695a80-c1f4-11eb-8048-5c403221e8ef.png)
![Screenshot_52](https://user-images.githubusercontent.com/53546539/120202709-e69a8780-c1f4-11eb-80f1-d76262c43e57.png)

**Comment by pkviet** [comment]
this will be hard to track since it depends on a third party plugin. But I'll check it out

**Comment by pkviet** [comment]
i haven't had time to investigate; i'm not bundling obs-ndi any more with my release. In order to get a compatible one, you'll have to compile obs-ndi against my version of libobs.lib .
