### ISSUE TITLE
Virtual audio cables do not work in Audio Input Capture

### ISSUE THREAD

**Issue by regstuff** [pkviet/obs-studio#56]
**Describe the bug**
OBS-ME does not seem to pick up virtual audio cables as Audio Input Capture. No sound comes through. The same setup works on OBS regular, so not sure if this is a bug or if I'm doing something wrong.

Tested with Virtual Cables such as [VB-Audio Cable](https://vb-audio.com/Cable/) & the paid [Virtual Audio Cable](https://vac.muzychenko.net/en/index.htm).

**To Reproduce**
1. Set audio channels as mono, stereo, 4.0 or any of those supported by regular OBS.
2. Add an Audio Input Capture to OBS ME. Choose a Virtual cable
3. Send something through the other side of the Virtual Cable.
4. No input seems to come through to OBS-ME
5. Repeat same process on Regular OBS and see the output.

**Expected behavior**
OBS-ME should be able to pick up the audio from the virtual audio cable.

**Desktop (please complete the following information):**
 - OS: Windows Version: 10.0 Build 18363 (release: 1909; revision: 1440; 64-bit)
 - Version: 26.0.2

**Additional context**
Looking at the logs, in OBS Regular I see:
```
11:50:29.032: WASAPI: Device 'Speakers / Headphones (Realtek Audio)' [48000 Hz] initialized
11:50:29.032: [Loaded global audio device]: 'Desktop Audio'
11:50:29.101: WASAPI: Device 'Line 1 (Virtual Audio Cable)' [48000 Hz] initialized
11:50:29.101: Switched to scene 'Scene'
```
However in OBS-ME, these devices fail to initialize.
```
11:52:09.358: [WASAPISource::TryInitialize]:[Speakers / Headphones (Realtek Audio)] Failed to get initialize audio client: 80070057
11:52:09.358: [WASAPISource::WASAPISource] Device '{0.0.0.00000000}.{7a35746f-a413-4b6c-8424-5efe8b53bc80}' not found.  Waiting for device
11:52:09.359: [Loaded global audio device]: 'Desktop Audio'
11:52:09.377: [WASAPISource::TryInitialize]:[Line 1 (Virtual Audio Cable)] Failed to get initialize audio client: 80070057
11:52:09.377: [WASAPISource::WASAPISource] Device '{0.0.1.00000000}.{cadeab89-ee49-4918-8d0d-31df5a53a1f7}' not found.  Waiting for device
```
Have attached logs of OBS-ME & OBS regular for reference.
[OBS-Regular Log.txt](https://github.com/pkviet/obs-studio/files/6602123/OBS-Regular.Log.txt)
[OBS-ME Log.txt](https://github.com/pkviet/obs-studio/files/6602125/OBS-ME.Log.txt)

**Comment by pkviet** [comment]
Hi
I've checked vac (muzychenko) on master branch and it works fine on my side, both with a desktop audio or audio input capture.
Haven't checked with the release though. I'll make a release soon; or you cna try your luck compiling master branch.
