### ISSUE TITLE
OBS v27

### ISSUE THREAD

**Issue by duncte123** [pkviet/obs-studio#58]
Are there any plans to upgrade this version to obs 27? I need the vst3 plugin but it does not work on version 27

**Comment by pxlphoto** [comment]
Yep, i Have the dame problem with rematrix plugin (that doesn't compile on linux either).
Let's hope in a new release.

**Comment by pkviet** [comment]
i've uploaded a new release (this will be the last; i'm retiring the project).

**Comment by duncte123** [comment]
> i've uploaded a new release (this will be the last; i'm retiring the project).

May I suggest archiving the repo in that case
