### ISSUE TITLE
DETECCIÓN DE TROYANO

### ISSUE THREAD

**Issue by todoporjesus** [pkviet/obs-studio#62]
1- Instalo la versión 26.0.2 sin problemas.

2- Instalo la versión 27.0.1, antivirus detecta troyano en: /obs-plugins/win-capture/inject-helper64.exe

![Instalando_obs_27 0 1](https://user-images.githubusercontent.com/87888737/126857773-3f945eab-28de-4c48-ad25-fe7e704dfd42.png)

3- Instalo la versión 27.0.1, con antivirus desactivado.
![Instalando_obs_27 0 1_antivirus_desactivado](https://user-images.githubusercontent.com/87888737/126857782-30de3c72-248b-431e-ba41-b0979d563dc0.png)

4- Adjunto archivo Crash 2021-07-24 01-29-15
[Crash 2021-07-24 01-29-15.txt](https://github.com/pkviet/obs-studio/files/6871914/Crash.2021-07-24.01-29-15.txt)

**Comment by pkviet** [comment]
nope there's no trojan, false positive.
