### ISSUE TITLE
[27.0.x] The hexadecagonal format is no longer available in audio device properties

### ISSUE THREAD

**Issue by mormegil6** [pkviet/obs-studio#66]
Since version 27.0.x, the maximum number of channels for audio device in ASIO Input Capture is 8 (7.1 setting). This happens regardless of general settings, where the audio channel number is set for 16.0.  

26.0.2 workflow:
Settings -> Audio -> General -> Channels -> 16.0
Sources -> add ASIO Input Capture -> format -> hexadecagonal -> 16 channels appear
screenshot: https://imgur.com/nL8eWev

27.0.x workflow:
Settings -> Audio -> General -> Channels -> the list ends with 7.1
screenshot: https://imgur.com/0f5Vbwq

The solution is to install previous version, 26.0.2.

**Comment by pkviet** [comment]
i 'm aware and fixed the issue a while ago although I didn't release anything. I might release an update, thanks to the current holidays.

**Comment by mormegil6** [comment]
It's great to hear that you already have a fix! I posted here since I did not see any report on this one, and I have been trying to set up a 16-channel stream (3rd order Ambisonic) for a few days. Also, I wanted to leave some trace of possible solution if anyone else was in need out there. 
Have a great holidays :)
