### ISSUE TITLE
OBS crashing regarding ffmpeg when switching scene collections or creating a new one.

### ISSUE THREAD

**Issue by datlaunchystark** [pkviet/obs-studio#74]
[Crash 2022-07-07 05-12-04.txt](https://github.com/pkviet/obs-studio/files/9063403/Crash.2022-07-07.05-12-04.txt)
[2022-07-07 05-11-33.txt](https://github.com/pkviet/obs-studio/files/9063405/2022-07-07.05-11-33.txt)

**Comment by pkviet** [comment]
can you repro the crash with vanilla obs ? it crashes in parts of the code that I didn't modify.
I managed to get a crash a few times but as of now, I fail to repro them.
It would help to have clear repro steps to facilitate the debugging.

**Comment by pkviet** [comment]
check the last release to see if it's fixed

**Comment by datlaunchystark** [comment]
I can't replicate it again with the new release so i think it was fixed :)
