### ISSUE TITLE
27.2.5 for local recording only?

### ISSUE THREAD

**Issue by Mishasama** [pkviet/obs-studio#75]
![image](https://user-images.githubusercontent.com/54498172/180387759-efabc66c-3dc9-4b1a-abc9-6e4d5a4a0c66.png)
![image](https://user-images.githubusercontent.com/54498172/180388209-f3f7b332-8640-46d2-9fc8-fb0f2c73c032.png)

**Comment by pkviet** [comment]
yeah i posted on the release section; didn't package correctly, will repost a release later today

**Comment by pkviet** [comment]
new build posted, should be fine now.

**Comment by Mishasama** [comment]
https://github.com/pkviet/obs-studio/releases/tag/v27.2.5
Fixed confirm. Thank you ♥
