### ISSUE TITLE
The plug-in called win-capture-audio does not work properly in OBS music edition.

### ISSUE THREAD

**Issue by bearwolfbw** [pkviet/obs-studio#78]
The plug-in called win-capture-audio does not work properly in OBS music edition. Win-capture-audio is a plug-in that distributes sounds from computers into obs tracks. You can set it up properly, but the voice meter does not go up. It's okay if you can't tell me how to solve it. I hope the developer doesn't have a headache because of the plug-in. I believe that some experienced people might be able to write a solution while this debate is still going on(I used a translator because I am Korean. I'm sorry if I write weird)

**Comment by pkviet** [comment]
Third party plugins are compiled against the original libobs library.
But obs ME uses a modified libobs. So it can't work.
You'll have to recompile the said plugin against my libobs.

**Comment by bearwolfbw** [comment]
Your tip solved my problem. Thank you for your sincere response

**Comment by blueraspberri** [comment]
Hi, so sorry to bother you. How did you recompile the plugin? I'm having the same issue and am struggling to fix it.
