### ISSUE TITLE
Request to Mainline srtmultiaudio

### ISSUE THREAD

**Issue by krakow10** [pkviet/obs-studio#85]
Hi, last summer I attempted to write code to enable multi audio track streaming for SRT, and you wrote the whole feature for me here: [srtmultiaudio](https://github.com/pkviet/obs-studio/tree/srtmultitrackaudio)
Do you think this can be mainlined?  I have been keeping a patch and building my own OBS to use it, but it would be nice to be able to use a maintained system package.

**Comment by pkviet** [comment]
yeah gonna PR multitrack audio since YT is experimenting with it with SRT.
